### ISSUE TITLE
<frozen importlib._bootstrap>:219: FutureWarning:

### ISSUE THREAD

**Issue by nilswagner** [WoLpH/numpy-stl#131] opened 2020-05-29 09:18 UTC
When I import stl in python3.8.2 I get

```
>>> import stl
<frozen importlib._bootstrap>:219: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>>> stl.__about__.__version__
'2.11.2'
```

How can I resolve the problem?

**Comment by WoLpH** [comment] 2020-05-29 13:00
It looks like the warning is about `numpy`, not `numpy-stl`. So I'm guessing your `numpy` needs to be upgraded.

For what it's worth, I can't replicate it:

```
# pip install numpy-stl
Collecting numpy-stl
  Downloading numpy-stl-2.11.2.tar.gz (484 kB)
     |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 484 kB 3.0 MB/s
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from numpy-stl) (1.17.4)
Collecting python-utils>=1.6.2
  Downloading python_utils-2.4.0-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from python-utils>=1.6.2->numpy-stl) (1.14.0)
Building wheels for collected packages: numpy-stl
  Building wheel for numpy-stl (setup.py) ... done
  Created wheel for numpy-stl: filename=numpy_stl-2.11.2-py3-none-any.whl size=17629 sha256=c71346e37bba95bb76a7635b5c1d29677b28312c7219b00358937aeba4711b2d
  Stored in directory: .cache/pip/wheels/f1/d8/17/4aaa75d86d7c4c5c026c28b0f695ea185336fa0a6e4ec2190c
Successfully built numpy-stl
Installing collected packages: python-utils, numpy-stl
  WARNING: The scripts stl, stl2ascii and stl2bin are installed in '.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  NOTE: The current PATH contains path(s) starting with `~`, which may not be expanded by all applications.
Successfully installed numpy-stl-2.11.2 python-utils-2.4.0
# python
Python 3.8.2 (default, Apr 27 2020, 15:53:34)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stl
```

**Comment by jarney1** [comment] 2020-11-17 22:27
Hey, I'm getting exactly the same warning. I have the latest version of Numpy.
I've done some searching around and no one has raised this issue with numpy directly.

Numpy==1.19.4
Numpy-stl==2.12.0
OS = MacOS BigSur (also happened on Catalina)
Python 3.8.5

happens on import of stl.

Steps to recreate (I use pyenv to manage multiple python versions):
```
pyenv global 3.8.5
python -m pip install numpy-stl
python
>>> import stl
```

output:
```
<frozen importlib._bootstrap>:219: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
```

If i do the same as above for python 3.7.7, I do not get the error

Is there any other info i can provide to help debug?
Thanks

**Comment by WoLpH** [comment] 2020-11-18 17:03
I've been able to reproduce is now. I've narrowed it down to the speedups code which is probably why I couldn't reproduce it earlier... I wasn't recompiling the speedups at that time.

I'm not sure what is causing it exactly however.

**Comment by WoLpH** [comment] 2020-11-21 22:45
Most likely fixed in the latest release. Let me know if you still have issues :)

**Closed by WoLpH** 2020-11-21 22:45 UTC
