### ISSUE TITLE
_speedups.ascii_read() causing locale change in linux env

### ISSUE THREAD

**Issue by gogela** [WoLpH/numpy-stl#169] opened 2021-03-19 15:30 UTC
Running functions that use _speedups.ascii_read() - ie. Mesh.from_file() causes change of locale settings:
typically:

```
from stl import mesh
import locale

print(locale.CODESET, locale.nl_langinfo(locale.CODESET))
x= return mesh.Mesh.from_file(filename)
print(locale.CODESET, locale.nl_langinfo(locale.CODESET))

OUTPUTS:
14 UTF-8
14 ANSI_X3.4-1968

```
**The problem apparently lies in:**

```
IF UNAME_SYSNAME == 'Linux':
        cdef locale_t new_locale = newlocale(LC_NUMERIC_MASK, 'C',
                                             <locale_t>NULL)
        cdef locale_t old_locale = uselocale(new_locale)
        freelocale(new_locale)
```

where the old_locale var gets populated from new_locale and furthermore never changed back

**Suggested change:**
LINE #21 (add): 
`locale_t LC_GLOBAL_LOCALE`
LINES #109,110
```
cdef locale_t old_locale = uselocale(LC_GLOBAL_LOCALE)
uselocale(new_locale)

```

**Comment by WoLpH** [comment] 2021-03-22 16:56
Wow... good catch. It never occurred to me that the change would affect other bits of code but that's indeed problematic.

This change was caused by a fix for this issue because some people had issues otherwise: https://github.com/WoLpH/numpy-stl/issues/52
I'll add this to my todo list :)

**Comment by gogela** [comment] 2021-03-23 07:37
sorry, closed by mistake.

**Comment by WoLpH** [comment] 2021-03-27 01:28
I found the issue... it was rather subtle. The code that was supposed to restore the locale was actually broken but nobody ever noticed because it was never executed. The code had a `return` a bit higher up and the restoring of the locale was not part of the `finally` clause.

In any case, I'll create a new release fixing this :)

**Closed** 2021-03-27 01:28 UTC
