### ISSUE TITLE
 help!!1 on windows 8.1,I found this proplem:  from stl import mesh   File "D:\Program Files\Anaconda3\lib\site-packages\stl\mesh.py", line 4, in <module>     class Mesh(stl.BaseStl): AttributeError: module 'stl' has no attribute 'BaseStl',thanks in  advance!

### ISSUE THREAD

**Issue by 675492062** [WoLpH/numpy-stl#68] opened 2018-03-05 02:49 UTC

**Comment by WoLpH** [comment] 2018-03-05 10:24
Most likely a duplicate of this issue: https://github.com/WoLpH/numpy-stl/issues/55

You need to remove the other stl library, they're incompatible

**Comment by 675492062** [comment] 2018-03-06 01:11
Thanks for your quick response.Really appreciate your advise.thanks again and again

**Closed** 2018-03-07 17:23 UTC

**Comment by AnalyticalTools** [comment] 2021-03-02 16:18
Hi, I uninstall stl library and install numoy-stl. The problem still persists...

**Comment by WoLpH** [comment] 2021-03-03 21:59
@AnalyticalTools It can also be caused by a file named `stl.py` in your directory or anywhere else in the Python path.

Something else has to be using the `stl` name.
